blog/urls.py
from django.urls import path
from .feeds import LatestPostsFeed

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}


admin.site.site_header = 'Мой учебный блог'
admin.site.index_title = 'Разделы админки Блога'
admin.site.site_title = 'Админка Блога'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """ Менеджер опубликованный постов. """

    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    """ Модель постов. """

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=100, verbose_name='Заголовок',)
    slug = models.SlugField(max_length=50, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts',
        verbose_name='Автор поста',
    )
    body = models.TextField(verbose_name='Текст поста')
    publish = models.DateTimeField(
        default=timezone.now,
        verbose_name='Опубликован',
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name='Статус поста',
    )
    tags = TaggableManager()

    objects = models.Manager()  # менеджер по умолчанию
    published = PublishedManager()  # менеджер возврата опубликованных постов

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-publish',)
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    """ Модель комментариев. """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Коментарий {self.name} на пост {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    """ Форма почтового сообщения. """
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """ Форма комментариев. """
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count

from .forms import EmailPostForm, CommentForm
from .models import Post


def post_list(request, tag_slug=None):
    """ Представление списка постов. """
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, settings.MAX_PAGES)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'posts': posts, 'tag': tag}
    return render(request, 'blog/list.html', context)


def post_detail(request, year: int, month: int, day: int, post: str):
    """ Детальное представление поста. """
    similar_posts_showing_count = 4
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
        id=post.id
    ).annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish'
    )[:similar_posts_showing_count]
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts
    }

    return render(request, 'blog/detail.html', context)


def post_share(request, post_id):
    """ Обработка формы предложки поста на почту. """

    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} советуем прочитать {post.title}"
            message = f"Прочитайте {post.title} на {post_url}\n\n" \
                      f"{cd['name']}\'s прокомментировал: {cd['comments']}"
            send_mail(subject, message, 'wegnagun@bk.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent
    }
    return render(request, 'blog/share.html', context)


@require_POST
def post_comment(request, post_id):
    """ Обработка формы комментариев. """

    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, 'blog/comment.html', context)

templates/base_.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>Мой блог</h2>
    <p>
      Это мой блог.
      Я написал {% total_posts %} поста(ов) =)
    </p>
    <p>
      <a href="{% url "blog:post_feed" %}">
      Подпишись на мою RSS рассылку
      </a>
    </p>
    <h3>Последние посты</h3>
    {% show_latest_posts 3 %}
    <h3>Самые комментируемые посты</h3>
    {% get_most_commented_posts as most_commented_posts %}
      <ul>
        {% for post in most_commented_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% endfor %}
      </ul>
  </div>
</body>
</html>

templates/blog/comment.html
{% extends "base_.html" %}
{% block title %}Добавить комментарий{% endblock %}
{% block content %}
{% if comment %}
  <h2>Ваш комментарий успешно добавлен!</h2>
  <p><a href="{{ post.get_absolute_url }}">Назад к посту</a></p>
{% else %}
  {% include "includes/comment_form.html" %}
{% endif %}
{% endblock %}

templates/blog/detail.html
{% extends "base_.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Опубликован {{ post.publish }}, {{ post.author }}
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url 'blog:post_share' post.id %}"> Поделиться постом</a>
  </p>
  <h2>Похожие посты</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    Похожих постов не найдено.
  {% endfor %}
  {% with comments.count as total_comments %}
    <h2>
      Всего комментариев: {{ total_comments }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Комментарий {{ forloop.counter }} {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
  {% empty %}
  <p>Комментариев нет</p>
  {% endfor %}
  {% include "includes/comment_form.html" %}
{% endblock %}

templates/blog/list.html
{% extends "base_.html" %}
{% load blog_tags %}
{% block title %}Мой блог{% endblock %}
{% block content %}
  <h1>Мой блог</h1>
  {% if tag %}
    <h2>Теги поста: "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
      {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Теги:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
    Опубликован {{ post.publish }}, {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "includes/paginator.html" with page=posts %}
{% endblock %}

templates/blog/share.html
{% extends "base_.html" %}
{% block title %}Поделиться постом{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail успешно отправлен</h1>
    <p>
      "{{ post.title }}" успешно отправлен {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Отправить "{{ post.title }}" по e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

templates/includes/comment_form.html
<h2>Добавить новый комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
  {{ form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Прокомментировать"></p>
</form>

templates/includes/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

templates/includes/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
    {% endif %}
    <span class="current">
      Страница {{ page.number }} из {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Далее</a>
    {% endif %}
  </span>
</div>